[package]
name = "mything"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[dependencies]
fib = { git = "https://github.com/worldofkerry-build-systems/rust-cargo-lib.git" }